# print("divizibilitate".count("i"))
# # s1 = 5*"bla"
# # print(s1)
# # s2 = s1.replace("bla","(z)",2)
# # print(s2)
# # sir = 'aBCdE'
# # print("\n", sir, sir.lower(), sir.upper(), sir.title())
# # print([' ab '.lstrip(), ' cd '.rstrip(), ' ef '.strip()])
# # print(['++--+-ab+'.lstrip('+'), '++--+-ab+'.lstrip('+-')])
# # print('laborator'.startswith('labo'), 'sala'.endswith('la'))
# # print('examen'.find('am'), 'examen'.find('exe'))
# # print('nota'.isalpha(), '1234'.isdigit(), 'nota 10'.isalnum())
# # l = 'Ana are mere.'.split(' '); print(l)
# # tel = '0000-111-222'.split('-'); print(tel)
# # s = " ".join(l); print(s)
# # nr_tel = "-".join(tel); print(nr_tel)
# # print(nr_tel)
# # print(list("abracadabra"))
# # print(list('123456789'))
# # print(1234/4, '--> ', list(str(float(1234/4))))
print(8)*5